"""Domain models — dataclasses for signals, votes, orders, and consensus."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from src.domain.enums import ConsensusMode, VoteSource
from src.strategies.pattern_detector import SignalDirection


@dataclass
class ConsensusVote:
    """Single directional vote from one source."""

    source: str  # algorithm / gemini / groq
    direction: SignalDirection  # BUY / SELL / NONE / NEUTRAL
    confidence: float  # 0-100
    rationale: dict[str, Any] = field(default_factory=dict)

    @property
    def reasoning_str(self) -> str:
        return self.rationale.get("reasoning", "")


@dataclass
class ConsensusResult:
    """Aggregated result of multi-AI majority voting."""

    direction: SignalDirection
    confidence: float
    votes: list[ConsensusVote] = field(default_factory=list)
    consensus_reached: bool = False
    agree_count: int = 0
    total_votes: int = 0
    mode: ConsensusMode = ConsensusMode.THREE_VOTE
    reject_reason: str | None = None

    @property
    def summary(self) -> str:
        parts = [
            f"{v.source}={v.direction.value}({v.confidence:.0f}%)"
            for v in self.votes
        ]
        mode_tag = "3V" if self.mode == ConsensusMode.THREE_VOTE else "2V-FB"
        return f"[{mode_tag} {self.agree_count}/{self.total_votes}] " + ", ".join(parts)


@dataclass
class PatternSignalResult:
    """Output from PatternDetector with quality score."""

    pattern: str
    direction: str
    pattern_score: float
    entry_ref_price: float
    invalidation_price: float
    stop_loss_price: float
    take_profit_price: float
    structural_rr: float
    meta: dict[str, Any] = field(default_factory=dict)


@dataclass
class SignalCandidate:
    """Pre-consensus signal candidate generated by StrategyEngine."""

    signal_id: str
    instrument: str
    direction: str
    pattern: str
    pattern_score: float
    entry_ref_price: float
    invalidation_price: float
    stop_loss_price: float
    take_profit_price: float
    structural_rr: float
    algo_confidence: float
    candle_close_time: str = ""


@dataclass
class OrderIntent:
    """Intent to place an order, output from RiskManager approval."""

    signal_id: str
    instrument: str
    direction: str
    units: int
    stop_loss: float
    take_profit: float
    risk_pct: float
    is_fallback: bool = False
    expires_at: str = ""
